### ISSUE TITLE
set up kanban board

### ISSUE THREAD

**Issue by bienvenuushindi** [bienvenuushindi/go-freelancer#19]
- [ ] [Kanban board](https://github.com/users/bienvenuushindi/projects/3/views/1)
- [ ] We are 4 people in this group ( @techwolf404 @AngomRanjan @businesskaniki  @bienvenuushindi )

![groupkanban](https://user-images.githubusercontent.com/26736582/205078094-ae3ac4b5-d300-457e-9378-cb8fe10c9e85.gif)

**Comment by Meltrust** [comment]
Hi @bienvenuushindi,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



### To highlight:

- All tasks have been pointed✔️ 

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

## Required Changes ♻️

- [ ] There are at least 2 tasks that don't have a description.  Kindly add descriptions to all the cards that don't have one.

![image](https://user-images.githubusercontent.com/57421823/205087981-bcf6730c-e36e-45de-b2fa-0bd46e8ca694.png)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Meltrust** [comment]
Hi @bienvenuushindi,


## Wow, you did it 🎉
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for implementing the changes requested by the previous reviewer 💪 🥇 ㊗️ 
### Well done!






### To highlight

- All tasks now have descriptions✔️ 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
